### ISSUE TITLE
several compilation errors when upgrading to 3.0 -- angular 10

### ISSUE THREAD

**Issue by DrRocket** [qlik-demo-team/qdt-components#240]
After upgrading to 3.0 I receive the following errors whenever I try to start my angular 10 project:

ERROR in node_modules/qdt-components/types/qdt-components.d.ts:73:12 - error TS1192: Module '".../node_modules/@types/prop-types/index"' has no default export.

node_modules/qdt-components/types/qdt-components.d.ts:104:12 - error TS1259: Module '".../node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

Deleting qdt-components.d.ts fixes these issues but of course i lose my types.

**Comment by yianni-ververis** [comment]
Check the template that I have with Angular 10

https://github.com/qlik-demo-team/qdt-angular-template

and the tsconfig

https://github.com/qlik-demo-team/qdt-angular-template/blob/master/tsconfig.json

**Comment by DrRocket** [comment]
Thanks for this!  Updating my tsconfig to match yours fixed the issues.
